// flow-typed signature: f0102a294647428eebd22d40caa7d90a
// flow-typed version: <<STUB>>/soundcloud-audio_v^1.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'soundcloud-audio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'soundcloud-audio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'soundcloud-audio/index' {
  declare module.exports: $Exports<'soundcloud-audio'>;
}
declare module 'soundcloud-audio/index.js' {
  declare module.exports: $Exports<'soundcloud-audio'>;
}
